In [1]:
import tensorflow as tf 
from tensorflow.contrib import learn 

# Contrib.learn's (predefined estimator(models) / custom estimator)

### contrib.learn’s out-of-the-box estimators (a fancy name for models), which we can train in a quick and efficient manner.

#### LinearRegressor() == Linear regression model to predict label value given observation of feature values. 
#### LogisticRegressor() == Logistic regression estimator for binary classification. 

#### LinearClassifier() == Linear model to classify instances into one of multiple possible classes. (When the number of possible classes is 2, this is binary classification.)

#### DNNRegressor() == A regressor for TensorFlow deep neural network (DNN) models. 
#### DNNClassifier() == A classifier for TensorFlow DNN models.



"""
1. We instantiate the estimator class to create our model:

   model = learn.< some_Estimator > () 


2. Then we fit it using our training data: 
   
   model.fit() 


3. We evaluate the model to see how well it does on some given dataset:
  
   model.evaluate() 


4. Finally, we use our fitted model to predict outcomes, usually for new data:
 
   model.predict()


"""

# 1) Linear Regressor

In [2]:
from sklearn import datasets, metrics, preprocessing

#Load Dataset
boston = datasets.load_boston() 

print(boston.data[:4])
print(boston.target[:4])

print(boston.data.shape)
print(boston.target.shape)

[[6.3200e-03 1.8000e+01 2.3100e+00 0.0000e+00 5.3800e-01 6.5750e+00
  6.5200e+01 4.0900e+00 1.0000e+00 2.9600e+02 1.5300e+01 3.9690e+02
  4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 0.0000e+00 4.6900e-01 6.4210e+00
  7.8900e+01 4.9671e+00 2.0000e+00 2.4200e+02 1.7800e+01 3.9690e+02
  9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 0.0000e+00 4.6900e-01 7.1850e+00
  6.1100e+01 4.9671e+00 2.0000e+00 2.4200e+02 1.7800e+01 3.9283e+02
  4.0300e+00]
 [3.2370e-02 0.0000e+00 2.1800e+00 0.0000e+00 4.5800e-01 6.9980e+00
  4.5800e+01 6.0622e+00 3.0000e+00 2.2200e+02 1.8700e+01 3.9463e+02
  2.9400e+00]]
[24.  21.6 34.7 33.4]
(506, 13)
(506,)


In [3]:
#Preprocess
x_data = preprocessing.StandardScaler().fit_transform(boston.data) 
y_data = boston.target

print(x_data[:4])
print(y_data[:4])

print(x_data.shape)
print(y_data.shape)

[[-0.41978194  0.28482986 -1.2879095  -0.27259857 -0.14421743  0.41367189
  -0.12001342  0.1402136  -0.98284286 -0.66660821 -1.45900038  0.44105193
  -1.0755623 ]
 [-0.41733926 -0.48772236 -0.59338101 -0.27259857 -0.74026221  0.19427445
   0.36716642  0.55715988 -0.8678825  -0.98732948 -0.30309415  0.44105193
  -0.49243937]
 [-0.41734159 -0.48772236 -0.59338101 -0.27259857 -0.74026221  1.28271368
  -0.26581176  0.55715988 -0.8678825  -0.98732948 -0.30309415  0.39642699
  -1.2087274 ]
 [-0.41675042 -0.48772236 -1.30687771 -0.27259857 -0.83528384  1.01630251
  -0.80988851  1.07773662 -0.75292215 -1.10611514  0.1130321   0.41616284
  -1.36151682]]
[24.  21.6 34.7 33.4]
(506, 13)
(506,)


In [4]:
NUM_STEPS = 200 
MINIBATCH_SIZE = 506

#Initialize Features
feature_columns = learn.infer_real_valued_columns_from_input(x_data)

#Initialize the estimator (Model)
reg = learn.LinearRegressor(feature_columns=feature_columns,
                            optimizer=tf.train.GradientDescentOptimizer(learning_rate=0.1)) 

#Training
reg.fit(x_data, boston.target, steps=NUM_STEPS,batch_size=MINIBATCH_SIZE)
MSE = reg.evaluate(x_data, boston.target, steps=1)

print(MSE)

Instructions for updating:
Please specify feature columns explicitly.
Instructions for updating:
Please use tensorflow/transform or tf.data.
Instructions for updating:
Please feed input to tf.data to support dask.
Instructions for updating:
Please access pandas data directly.
Instructions for updating:
Please use tensorflow/transform or tf.data.
Instructions for updating:
Please convert numpy dtypes explicitly.
Instructions for updating:
Please specify feature columns explicitly.
Instructions for updating:
Please switch to tf.contrib.estimator.*_head.
Instructions for updating:
Please replace uses of any Estimator from tf.contrib.learn with an Estimator from tf.estimator.*
Instructions for updating:
When switching to tf.estimator.Estimator, use tf.estimator.RunConfig instead.
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x00000226BCEAFCF8>, '_master':

INFO:tensorflow:Saving checkpoints for 200 into C:\Users\DELL\AppData\Local\Temp\tmpp790bf81\model.ckpt.
INFO:tensorflow:Loss for final step: 21.899305.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
INFO:tensorflow:Starting evaluation at 2018-12-23-11:31:45
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\DELL\AppData\Local\Temp\tmpp790bf81\model.ckpt-200
INFO:tensorflow:Running local_init_op.
IN

In [5]:
#Preidction

x_data_1 = x_data[:10]
pred =reg.predict(x= x_data_1,as_iterable=False)
pred

Instructions for updating:
The default behavior of predict() is changing. The default value for
as_iterable will change to True, and then the flag will be removed
altogether. The behavior of this flag is described below.
Instructions for updating:
Please switch to predict_scores, or set `outputs` argument.
Instructions for updating:
The default behavior of predict() is changing. The default value for
as_iterable will change to True, and then the flag will be removed
altogether. The behavior of this flag is described below.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available 

array([30.099747, 25.007069, 30.564701, 28.610931, 27.94912 , 25.247356,
       22.981886, 19.513483, 11.49988 , 18.895947], dtype=float32)

In [6]:
#Ground Truth
y_data[:10]

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9])

# 2) Logistic Regressor

In [7]:
import sys 
import numpy as np 
from tensorflow.examples.tutorials.mnist import input_data 

DATA_DIR = '/tmp/data' if not 'win32' in sys.platform else "c:\\tmp\\data" 

In [8]:
data = input_data.read_data_sets(DATA_DIR, one_hot=False) 

x_data, y_data = data.train.images,data.train.labels.astype(np.int32) 
x_test, y_test = data.test.images,data.test.labels.astype(np.int32) 


Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use urllib or similar directly.
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting c:\tmp\data\train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting c:\tmp\data\train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting c:\tmp\data\t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting c:\tmp\data\t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [9]:
#Note that in this case, due to the requirement of the estimator, we pass the target in its class label form:
one_hot=False

In [10]:
NUM_STEPS = 2000 
MINIBATCH_SIZE = 128

#Initialize Feature_column
feature_columns = learn.infer_real_valued_columns_from_input(x_data)

#Initialize DNN Estimator
dnn = learn.DNNClassifier(feature_columns=feature_columns,hidden_units=[200],n_classes=10,optimizer=tf.train.ProximalAdagradOptimizer(learning_rate=0.2))

#Train the Model
dnn.fit(x=x_data,y=y_data, steps=NUM_STEPS,batch_size=MINIBATCH_SIZE)

#Print Accuracy
test_acc = dnn.evaluate(x=x_test,y=y_test, steps=1)["accuracy"] 
print('test accuracy: {}'.format(test_acc))



Instructions for updating:
Please switch to tf.contrib.estimator.*_head.
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x00000226D427BF28>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_train_distribute': None, '_eval_distribute': None, '_device_fn': None, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_log_step_count_steps': 100, '_protocol': None, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': 'C:\\Users\\DELL\\AppData\\Local\\Temp\\tmp9va63u9i'}
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op

In [12]:
# Evaluate Metrix
from sklearn.metrics import confusion_matrix

y_pred = dnn.predict(x=x_test,as_iterable=False) 
class_names = ['0','1','2','3','4','5','6','7','8','9']    
cnf_matrix = confusion_matrix(y_test, y_pred) 
cnf_matrix

INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\DELL\AppData\Local\Temp\tmp9va63u9i\model.ckpt-2000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


array([[ 972,    1,    0,    0,    1,    1,    2,    1,    2,    0],
       [   0, 1126,    2,    2,    0,    0,    2,    0,    3,    0],
       [   6,    3, 1001,    2,    3,    1,    2,    8,    6,    0],
       [   1,    0,    3,  998,    0,    0,    0,    3,    4,    1],
       [   2,    0,    5,    1,  963,    0,    2,    2,    1,    6],
       [   3,    0,    0,   14,    1,  859,    6,    1,    6,    2],
       [   4,    3,    0,    1,    3,    3,  944,    0,    0,    0],
       [   1,    6,    8,    2,    1,    0,    0, 1004,    1,    5],
       [   4,    0,    3,    7,    4,    1,    6,    2,  945,    2],
       [   5,    4,    0,    8,   14,    2,    1,    9,    1,  965]],
      dtype=int64)